highland_rand_to_best_output = r'C:\project\ocp\networks\highland\output\highland.rand_to_best.output.txt'
highland_rand2_output = r'C:\project\ocp\networks\highland\output\highland.rand2.output.txt'
highland_current_to_rand_output=r'C:\project\ocp\networks\highland\output\highland.current_to_rand.output.txt'
highland_no_crossover_output=r'C:\project\ocp\networks\highland\output\highland.no_crossover.output.txt'
highland_current_to_best_output=r'C:\project\ocp\networks\highland\output\highland.current_to_best.output.txt'
highland_blank_output=r'C:\project\ocp\networks\highland\output\highland.blank_output.txt'

bundesliga_blank_output=r'C:\project\ocp\networks\bundesliga\output\bundesliga.blank_output.txt'
bundesliga_current_to_best_output=r'C:\project\ocp\networks\bundesliga\output\bundesliga.current_to_best.output.txt'
bundesliga_no_crossover_output=r'C:\project\ocp\networks\bundesliga\output\bundesliga.no_crossover.output.txt'
bundesliga_rand2_output=r'C:\project\ocp\networks\bundesliga\output\bundesliga.rand2.output.txt'
bundesliga_rand_to_best_output=r'C:\project\ocp\networks\bundesliga\output\bundesliga.rand_to_best.output.txt'
bundesliga_current_to_rand_output=r'C:\project\ocp\networks\bundesliga\output\bundesliga.current_to_rand.output.txt'

highschool_rand_to_best_output = r'C:\project\ocp\networks\highschool\output\highschool.rand_to_best.output.txt'
highschool_rand2_output = r'C:\project\ocp\networks\highschool\output\highschool.rand2.output.txt'
highschool_current_to_rand_output=r'C:\project\ocp\networks\highschool\output\highschool.current_to_rand.output.txt'
highschool_no_crossover_output=r'C:\project\ocp\networks\highschool\output\highschool.no_crossover.output.txt'
highschool_current_to_best_output=r'C:\project\ocp\networks\highschool\output\highschool.current_to_best.output.txt'
highschool_blank_output=r'C:\project\ocp\networks\highschool\output\highschool.blank_output.txt'

hiv_rand_to_best_output = r'C:\project\ocp\networks\hiv\output\hiv.rand_to_best.output.txt'
hiv_rand2_output = r'C:\project\ocp\networks\hiv\output\hiv.rand2.output.txt'
hiv_current_to_rand_output=r'C:\project\ocp\networks\hiv\output\hiv.current_to_rand.output.txt'
hiv_no_crossover_output=r'C:\project\ocp\networks\hiv\output\hiv.no_crossover.output.txt'
hiv_current_to_best_output=r'C:\project\ocp\networks\hiv\output\hiv.current_to_best.output.txt'
hiv_blank_output=r'C:\project\ocp\networks\hiv\output\hiv.blank_output.txt'

league_rand_to_best_output = r'C:\project\ocp\networks\league\output\league.rand_to_best.output.txt'
league_rand2_output = r'C:\project\ocp\networks\league\output\league.rand2.output.txt'
league_current_to_rand_output=r'C:\project\ocp\networks\league\output\league.current_to_rand.output.txt'
league_no_crossover_output=r'C:\project\ocp\networks\league\output\league.no_crossover.output.txt'
league_current_to_best_output=r'C:\project\ocp\networks\league\output\league.current_to_best.output.txt'
league_blank_output=r'C:\project\ocp\networks\league\output\league.blank_output.txt'

revolution_current_to_best_output=r'D:\profile\2018\codes\py\ocpde\networks\revolution\output\revolution.current_to_best.output.txt'
revolution_current_to_rand_output=r'D:\profile\2018\codes\py\ocpde\networks\revolution\output\revolution.current_to_rand.output.txt'
revolution_no_crossover_output=r'D:\profile\2018\codes\py\ocpde\networks\revolution\output\revolution.no_crossover.output.txt'
revolution_rand2_output=r'D:\profile\2018\codes\py\ocpde\networks\revolution\output\revolution.rand2.output.txt'
revolution_rand_to_best_output=r'D:\profile\2018\codes\py\ocpde\networks\revolution\output\revolution.rand_to_best.output.txt'
revolution_blank_output=r'D:\profile\2018\codes\py\ocpde\networks\revolution\output\revolution.blank_output.txt'

zachary_rand_to_best_output = r'C:\project\ocp\networks\zachary\output\zachary.rand_to_best.output.txt'
zachary_rand2_output = r'C:\project\ocp\networks\zachary\output\zachary.rand2.output.txt'
zachary_current_to_rand_output=r'C:\project\ocp\networks\zachary\output\zachary.current_to_rand.output.txt'
zachary_no_crossover_output=r'C:\project\ocp\networks\zachary\output\zachary.no_crossover.output.txt'
zachary_current_to_best_output=r'C:\project\ocp\networks\zachary\output\zachary.current_to_best.output.txt'
zachary_blank_output=r'C:\project\ocp\networks\zachary\output\zachary.blank_output.txt'

macaques_current_to_best_output=r'D:\profile\2018\codes\py\ocpde\networks\macaques\output\macaques.current_to_best.output.txt'
macaques_current_to_rand_output=r'D:\profile\2018\codes\py\ocpde\networks\macaques\output\macaques.current_to_rand.output.txt'
macaques_no_crossover_output=r'D:\profile\2018\codes\py\ocpde\networks\macaques\output\macaques.no_crossover.output.txt'
macaques_rand2_output=r'D:\profile\2018\codes\py\ocpde\networks\macaques\output\macaques.rand2.output.txt'
macaques_rand_to_best_output=r'D:\profile\2018\codes\py\ocpde\networks\macaques\output\macaques.rand_to_best.output.txt'
macaques_blank_output=r'D:\profile\2018\codes\py\ocpde\networks\macaques\output\macaques.blank_output.txt'

windsurfers_current_to_best_output=r'D:\profile\2018\codes\py\ocpde\networks\windsurfers\output\windsurfers.current_to_best.output.txt'
windsurfers_current_to_rand_output=r'D:\profile\2018\codes\py\ocpde\networks\windsurfers\output\windsurfers.current_to_rand.output.txt'
windsurfers_no_crossover_output=r'D:\profile\2018\codes\py\ocpde\networks\windsurfers\output\windsurfers.no_crossover.output.txt'
windsurfers_rand2_output=r'D:\profile\2018\codes\py\ocpde\networks\windsurfers\output\windsurfers.rand2.output.txt'
windsurfers_rand_to_best_output=r'D:\profile\2018\codes\py\ocpde\networks\windsurfers\output\windsurfers.rand_to_best.output.txt'
windsurfers_blank_output=r'D:\profile\2018\codes\py\ocpde\networks\windsurfers\output\windsurfers.blank_output.txt'
